# Generated by Django 5.2.17 on 2026-09-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('author', models.CharField(db_index=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=150, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('published_year', models.IntegerField(blank=True, null=True)),
                ('book_type', models.CharField(choices=[('POLITICS', 'Politics'), ('HISTORY', 'History'), ('FARMING', 'Farming'), ('ECONOMIC', 'Economic'), ('GENERAL', 'General'), ('SCIENCE', 'Science'), ('LITRATURE', 'Litrature'), ('OTHER', 'Other')], default='HISTORY', max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('borrowed', models.BooleanField(default=False)),
                ('borrowed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('borrowed_on', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('book_notes', models.FileField(blank=True, null=True, upload_to='book_notes/')),
                ('favorite', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('buyed_on', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book')),
            ],
        ),
    ]
