# Generated by Django 5.2.17 on 2026-09-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
